### ISSUE TITLE
[ERROR] qemu not booting up for me

### ISSUE THREAD

**Issue by abhra2020-smart** [chibicitiberiu/nanobyte_os#3]
Hi! First, you are the best OS making tutor! But QEMU is not booting up for me.

Command: qemu-system-i386 -fda orangeos-img.img

Output:
Unable to init server: Could not connect: Connection refused
WARNING: Image format was not specified for 'orangeos-img.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
gtk initialization failed

File Structure:
OrangeOs
   |
    --->/src
            |
             ---> boot.asm
    --->/dist
           |
            ---> orangeos-img.img
            ---> boot.bin
    --->Makefile

Is it related to me not having a Linux server?

**Comment by Aakash2705** [comment]
Are you running this is in something like WSL or a Docker container? The error seems like qemu didn't connect to a display server.
If you are on windows:
just install qemu through their website and point it it to the build file in windows.

**Comment by abhra2020-smart** [comment]
I'm running on WSL

**Comment by abhra2020-smart** [comment]
Thanks for the help

**Comment by abhra2020-smart** [comment]
I tried, but unfortunately, no change :(

**Comment by abhra2020-smart** [comment]
Make is not working. I have it. The tab problem.

**Comment by chibicitiberiu** [comment]
Really sorry about not responding sooner, I'm not getting notifications for new issues for some reason.

Have you followed the WSL guide in [this video?](https://www.youtube.com/watch?v=TgIdFVOV_0U&t=2s). You need to install an X server on your Windows host (like VcxSrv), and then setup the DISPLAY variable.
